version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    insecure-external-code-execution: allow
    versioning-strategy: "increase"
    schedule:
      interval: "daily"
    groups:
      python-dependencies:
        patterns:
        - "*"
